# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artist',
            field=models.CharField(default="Kanye West", max_length=200),
            preserve_default=False,
        ),
    ]
